tractordev/wanix

- Makefile
at first run `make dev` is missing the kernel and shell. The browser shows 404 for those requests.
> fix make dev target

- go.mod
- go.sum
- internal/mountablefs/mountablefs.go
- internal/mountablefs/mountablefs_test.go
- kernel/fs/fs.go
Pulling in `mountablefs` from toolkit-go since it's not quite finished and it'll be easier to develop here for now. Also dropped the go.mod replacement that assumes you have toolkit-go cloned next to this repo.
> mountablefs

- internal/indexedfs/indexedfs.js
Closes #24
Calling `IDBObjectStore.delete()` wasn't working so I switched to `IDBCursor.delete()`. I also fixed a bug where it wouldn't delete the base path.
> indexedfs: fix `deleteAll`

- internal/app/terminal/index.html
- shell/builtin.go
- shell/main.go
Closes #16 
This command walks the file system, creates a tree graph of it's structure, and prints that graph to the console. Generating the file tree can take a moment, especially if the file system is networked, so it'll print a loading message after a second to stderr to notify the user. 
This PR also enables terminal scrollback, 500 lines to be exact.
Having options for excluding certain directories (e.g. `.gitignore`) or mounts would be nice. Currently it doesn't follow `.git/` or `/sys/dev/` unless you directly pass them as the argument.
Only printing directories would be useful as well.
> Tree Command

- internal/app/terminal/index.html
Closes #43 
Just telling xterm.js to ignore these key commands and kicking the can down to the OS/browser to handle copy/paste.
> terminal: allow copy pasting

- Makefile
- internal/jsutil/jsutil.go
- kernel/main.go
- kernel/proc/exec/exec.go
- kernel/web/lib/syscall.js
- kernel/web/lib/task.js
- kernel/web/ui.go
- shell/main.go
Closes #35 
Added `kernel.version` syscall. The kernel version is set in the Makefile and linked into the build.
Added `WanixSyscall` helper to make syscalls easier and more readable. I switched syscalls to this new helper where applicable. Includes `WanixSyscallResp` to access the `response` itself as well.
> Print version and add `WanixSyscall` helper

- kernel/web/lib/host.js
- shell/download.go
- shell/smallcmds.go
Closes #40
Allows downloading a file or directory to the host computer. 
Implementation deviates slightly as I had troubles getting `archive/tar` to work properly. Both `archive/tar` and `archive/zip` have issues writing subdirectories. Weirdly this only happens if not using compression, otherwise it works fine.
In the future we can debug this and add options for file and compression formats.
> Download command

- internal/app/terminal/index.html
- kernel/proc/js.go
- kernel/proc/proc.go
- kernel/tty/js.go
- kernel/tty/tty.go
add resize syscall, but only impacts new processes. include ROWS, COLS, and TERM env vars. this should be enough for getting programs like micro to start, but to actually resize the terminal while running will require a solution for signals.
closes #36 for purposes of unblocking #6
> starts terminal resizing, adds env vars needed to start micro

- go.mod
- go.sum
- internal/indexedfs/indexedfs.go
- internal/indexedfs/indexedfs.js
- internal/mountablefs/mountablefs.go
- internal/osfs/osfs.go
- kernel/fs/fs.go
- kernel/web/lib/syscall.js
- shell/copy.go
- shell/main.go
- shell/open.go
- shell/smallcmds.go
- shell/watch.go
Closes #38
- Implemented `watch` syscall using RPC, since we need to send structured data to/from the kernel process.
- Added `Watch` support to `mountablefs`.
- Converted `osfs` to use `io/fs` paths instead of Unix ones, for better compatibility with other file systems.
- Implemented `open`, `watch`, and `unwatch` shell commands
> `watch` syscall and `open` command

- kernel/fs/fs.go
I saw that there were some changes to how fs.fsys is used. But I'm new to the codebase, and still exploring the project.
> Correct fs.fsys usage

- .gitignore
- Makefile
- build/build-pkgs/imports/go.mod
- build/build-pkgs/imports/go.sum
- build/build-pkgs/imports/imports.go
- build/build-pkgs/main.go
- internal/export/exportapp.sh
- internal/export/main.go
- internal/indexedfs/indexedfs.go
- kernel/fs/fs.go
- shell/main.go
- shell/smallcmds.go
- shell/util.go
Closes #37
Closes #56
This PR implements compiling build tool's `pkg.zip` from source and running it in a shell script. Had to shave a yak or two in the process, but it finally works!
One thing to note: `compile.wasm` and `link.wasm` are compiled from the user's local Go installation. This could cause compatibility issues between users in the future, as their Wanix instances may be compiled with different Go versions, but it's the simplest way to complete this for now.
> Exportapp and compiling build tool from source

- go.mod
- go.sum
- shell/main.go
- shell/preprocessor.go
I forked the go-posix library and added the ability to expand numbered variables (e.g. `/$1/bar/$2 -> /foo/bar/baz`). Cleaned unecessary functions as well.
> shell: support script argument expansion

- CONTRIBUTING.md
Tiny start on `CONTRIBUTING.md` - I think it will be particularly useful for developers who want to get started. I found something minor to help out in vscode, I am sure there will be more.
> saves a red squiggle for vscode workspace settings cuz syscall/js

- CONTRIBUTING.md
- Dockerfile
as the title suggests, I don't have any strong opinions about my work here. I tested it insofar as running in docker and pulling up localhost:7777 As I mentioned before this could be a nice way to get up and running quickly as local dev environments are so finicky
> Working Dockerfile, nothing fancy

- internal/indexedfs/indexedfs.go
- internal/indexedfs/indexedfs.js
- kernel/web/lib/duplex.js
- kernel/web/lib/task.js
- kernel/web/lib/wasm.js
- shell/smallcmds.go
Closes #79 
Turns out one of those pesky `todo`s came back to haunt me, go figure. The panic was due to how we resolve filesystem errors to error codes for syscalls. `indexedfs` helper calls were returning generic `syscall/js.Error` errors which we couldn't properly resolve in `jsutil.go:ToJSError()`, causing a panic in the `os` package which expected to find an error code.
I fixed this by explicitly stating which Go error to return when erroring in the JS helper. I also finished the `mv` command and did some other cleanup.
> Fix `indexedfs` error handling and complete `mv` command

- dev/bootloader.js
- dev/bundle.go
- dev/initdata.go
- dev/initdata.tmpl
- dev/server.go
- internal/app/terminal/index.html
- internal/indexedfs/indexedfs.go
- kernel/fs/fs.go
- kernel/main.go
- kernel/proc/proc.go
- kernel/web/lib/task.js
- kernel/web/lib/wasm.js
- kernel/web/lib/worker.js
- shell/main.go
- shell/util.go
Closes #89
Closes #88
Closes #66
Live editing is here! 
One small footgun: until #69 is completed any errors produced by build in `proc.Spawn` won't be reported to the user.
> Include shell source and build source directories in `proc.Spawn`

- kernel/proc/proc.go
- shell/preprocessor.go
- shell/smallcmds.go
Closes #94
I reordered the preprocessor so variable expansion happens first, which allows you to things like `echo $MICRO_CONFIG_HOME/*`. The example in the issue uses `rm` which had an outstanding TODO so I completed that as well.
Added a log when building the shell at startup too.
> shell: fix glob expansion and `rm` multiple arguments

- dev/bootloader.js
- internal/githubfs/githubfs.go
- internal/indexedfs/indexedfs.go
- kernel/fs/fs.go
> GitHub Filesystem

- go.mod
- go.sum
- internal/githubfs/githubfs.go
Forgot to reset `file.dirty` flag after `Sync` is called. `toolkit-go` needed updating as well.
> Githubfs fix and update `toolkit-go`

- internal/procfs/procfs.go
- kernel/fs/fs.go
- kernel/main.go
- kernel/proc/proc.go
- kernel/tty/tty.go
Closes #70 
Basic implementation of `procfs`. Lists running processes under `/sys/proc` indexed by PID. Reading a PID file returns the `proc.Process` serialized to JSON. The format can be changed if required. In the future I'd like to add more structured data and queries using the filesystem.
This PR also reorganizes the kernel, removing the `engine` package. I found it confusing initially, and more of a hinderance than a benefit. I needed more flexibility and control. Rewriting the startup code by hand was simple; now the code is explicit and much easier to follow. I'm not sure what problem `engine` was trying to solve. That being said, the commit can easily be reverted and procfs updated with minor changes if need be.
> Procfs and Kernel refactor

- Makefile
- external/micro/wanix_vendor.patch
> micro: accept relative file paths

- external/hugo/wanix_vendor.patch
- kernel/fs/js.go
> hugo: change default options to support githubfs

- .github/workflows/build.yml
This is a first pass at a build workflow for GitHub Actions. It doesn't produce artifacts, but it successfully builds everything. From scratch it takes about 10-12 minutes, and then with dependency Docker builds cached it takes about 5 minutes. Probably half that time is just setting up and tearing down cache. Not ideal, but good enough.
Closes #160
> github: workflow for github actions ci

- external/v86/patch/starter.js
to build with current v86, without this patch you'll see 
```
STEP 9/14: RUN PATH="${HOME}/.cargo/bin:${PATH}" make all && rm -rf closure-compiler gen lib src .cargo cargo.toml Makefile
mkdir -p closure-compiler
wget -nv -O closure-compiler/compiler.jar https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20210601/closure-compiler-v20210601.jar
Connecting to repo1.maven.org (199.232.192.209:443)
saving to 'closure-compiler/compiler.jar'
compiler.jar         100% |********************************| 12.0M  0:00:00 ETA
'closure-compiler/compiler.jar' saved
mkdir -p build
ls -lh build/v86_all.js
ls: build/v86_all.js: No such file or directory
make: [Makefile:104: build/v86_all.js] Error 1 (ignored)
java -jar closure-compiler/compiler.jar \
--js_output_file build/v86_all.js\ …
```
> v86: update to work with latest v86

- vfs/pipe/buffer.go
- vfs/pipe/pipe.go
- vfs/pipe/pipe_test.go
- vfs/pipe/portfile.go
The #pipe device files previously reported a static size of 0 in their file stats, which did not reflect the amount of data pending in their read buffers. This commit implements the functionality to dynamically report the current length of a pipe's read buffer as the file's size.
This was achieved by:
- Adding a thread-safe Size() method to pipe.Buffer to expose the internal buffer length.
- Exposing this size through a new method on pipe.Port.
- Updating PortFile.Stat() to call this method and pass the dynamic size to fskit.Entry, ensuring the file mode is correctly set to include fs.ModeNamedPipe.
Fixes #215
> pipe: report buffer size as file size
